version: '3.1'
services:

  jenkins-server:
    build: .
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    tty: true
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./sock:/var/run/docker.sock
